name: ucp
description: "Ucp Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  super_profile_picture: ^1.0.0
  date_time_format: ^2.0.1
  ionicons: ^0.2.2
  loading_animation_widget: ^1.3.0
  firebase_core:
  flutter_local_notifications: ^17.2.3
  firebase_messaging:
  gap:
  internet_connection_checker_plus: ^2.5.2
  flutter_slidable: ^3.1.0
  get:
  device_info_plus:
  dio:
  url_launcher:
  dio_cache_interceptor:
  dio_logging_interceptor:
  equatable:
  cherry_toast: ^1.11.0
  flutter_flavor:
  flutter_dotenv:
  camera: ^0.11.0+2
  envied: ^0.3.0+3
  path_provider:
  image:
  rxdart:
  liquid_pull_to_refresh: ^3.0.1
  image_cropper: ^8.0.2
  image_picker: ^1.0.2
  msh_checkbox: ^2.0.1
  flutter_staggered_animations:
  permission_handler:
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  animate_do: ^3.1.2
  intl: ^0.19.0
  rich_text_widget: ^0.2.7
  pin_code_fields: ^8.0.1
  http: ^1.2.2
  flutter_country_state: ^1.0.0
  flutter_typeahead: ^5.2.0
  custom_grid_view: ^0.0.1
  flutter_udid:
  flutter_animate:
  provider:
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  badges: ^3.1.2
  custom_refresh_indicator: ^4.0.1
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet


dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6
  injectable_generator:


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bottomNavIcons/selected/
    - assets/images/bottomNavIcons/unseleted/
    - assets/images/signUp/
    - assets/images/memberBg1.png
    - assets/images/memberBg2.png
    - assets/images/memberBg3.png
    - assets/images/password_alert.png
    - assets/images/password_check.png



  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/font/dmSans/DMSans-Light.ttf
        - asset: assets/font/dmSans/DMSans-Medium.ttf
        - asset: assets/font/dmSans/DMSans-Regular.ttf

    - family: Creato Display
      fonts:
        - asset: assets/font/creatoDisplay/CreatoDisplay-Bold.otf
        - asset: assets/font/creatoDisplay/CreatoDisplay-Medium.otf
        - asset: assets/font/creatoDisplay/CreatoDisplay-Regular.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
